version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - finnetwork
  api:
    container_name: dev-api
    build: ./api
    environment:
      - SECRET_KEY=kkaw*&u0nl0i0#50e6%6y#ab*_jd-b_8v4-lsjj1j3@mg@r&a
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./api:/app/api
    ports:
      - '8000:8000'
    networks:
      - finnetwork
    restart: always
    depends_on:
      - db

volumes:
  db:

networks:
  finnetwork:
      driver: bridge

