# Generated by Django 2.2.12 on 2020-10-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('idPessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('dataNascimento', models.DateField()),
            ],
            options={
                'db_table': 'pessoas',
            },
        ),
    ]
