# Generated by Django 2.2.12 on 2020-10-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='dataNascimento',
            field=models.DateTimeField(),
        ),
    ]
