# Generated by Django 2.2.12 on 2020-10-06 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('idTransacao', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dataTransacao', models.DateField(auto_now_add=True)),
                ('idConta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.Conta')),
            ],
            options={
                'db_table': 'transacao',
            },
        ),
    ]
